//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerDiaryDataAggregator.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PowerDiaryDataAggregator.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Hourly_PeopleEntered {
            get {
                return ResourceManager.GetString("Hourly_PeopleEntered", resourceCulture);
            }
        }
        
        internal static string Hourly_PeopleExited {
            get {
                return ResourceManager.GetString("Hourly_PeopleExited", resourceCulture);
            }
        }
        
        internal static string Hourly_HighFive {
            get {
                return ResourceManager.GetString("Hourly_HighFive", resourceCulture);
            }
        }
        
        internal static string Hourly_CommentsMade {
            get {
                return ResourceManager.GetString("Hourly_CommentsMade", resourceCulture);
            }
        }
        
        internal static string Hourly_Time {
            get {
                return ResourceManager.GetString("Hourly_Time", resourceCulture);
            }
        }
        
        internal static string KeyNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("KeyNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        internal static string Minutely_PersonEntered {
            get {
                return ResourceManager.GetString("Minutely_PersonEntered", resourceCulture);
            }
        }
        
        internal static string Minutely_PersonExited {
            get {
                return ResourceManager.GetString("Minutely_PersonExited", resourceCulture);
            }
        }
        
        internal static string Minutely_HighFive {
            get {
                return ResourceManager.GetString("Minutely_HighFive", resourceCulture);
            }
        }
        
        internal static string Minutely_CommentsMade {
            get {
                return ResourceManager.GetString("Minutely_CommentsMade", resourceCulture);
            }
        }
    }
}
